language: cpp

sudo: required
dist: trusty

matrix:
  include:
    # Native linux compilation
    - os: linux
      addons:
        apt:
          packages:
            - libasound2-dev
      compiler: gcc

    # Cross-platform windows compilation
    - os: linux
      compiler: i686-w64-mingw32-g++
      before_install:
        - sudo dpkg --add-architecture i386
        - echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mxeapt.list
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
        - sudo apt-get -qq update
        - sudo apt-get install -y mxe-i686-w64-mingw32.static-binutils mxe-i686-w64-mingw32.static-gcc
      before_script:
        - export PATH=/usr/lib/mxe/usr/bin:$PATH
      env:
        - CROSS_PREFIX=i686-w64-mingw32.static-

    # Native MacOS compilation
    - os: osx

script:
  - mkdir build && cd build && ${CROSS_PREFIX}cmake ../desktop && make && ls -l

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file_glob: true
  file: scherzo-*
  skip_cleanup: true
  on:
    tags: true

